# Testing docker-compose File
version: '3.7'
services:
    db:
        image: mariadb:10.9
        container_name: lol-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mariadb
        profiles: ['testing', 'local']
        volumes:
            - mariadb_data-lol:/var/lib/mysql
        networks:
            - lol
    app:
        image: ghcr.io/phinocio/loadorderlibrary:testing
        container_name: lol-testing
        restart: unless-stopped
        entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate:fresh --seed && exec php-fpm"
        env_file: .env
        user: '2000:2000'
        profiles: ['testing', 'local']
        ports:
            - '127.0.0.1:9000:9000'
        volumes:
            - ./storage/:/var/www/storage/
        networks:
            - lol
        depends_on: [db]
    nginx:
        image: nginx:1.25.0-alpine
        container_name: lol-nginx
        restart: unless-stopped
        profiles: ['local']
        ports:
            - '8000:80'
        volumes:
            - ./public:/var/www/public
            - ./docker/testing/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/testing/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - /var/log/nginx/lol-testing:/var/log/nginx
        networks:
            - lol
        depends_on: [app]

networks:
    lol:
        driver: bridge

volumes:
    mariadb_data-lol:
