---
# Local Development docker-compose File.
services:
    # db:
    #     image: mariadb:10.9
    #     container_name: lol-dev-db
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #         SERVICE_NAME: mariadb
    #     ports:
    #         - '3306:3306'
    #     volumes:
    #         - lol-testing-db:/var/lib/mysql
    #     networks:
    #         - lol
    #         - lol-db
    app:
        build:
            context: .
            args:
                uid: 1000
                gid: 2010
            dockerfile: docker/dev/app/Dockerfile
            target: app-dev
        image: loadorderlibrary:dev
        container_name: lol-dev-app
        restart: unless-stopped
        entrypoint: sh -c "exec php-fpm"
        volumes:
            - ./:/srv/dev.loadorderlibrary.com
            - ../../APIs/loadorderlibrary-api/storage/app/uploads:/srv/dev.loadorderlibrary.com/storage/app/uploads
        networks:
            - lol
            - lol-db
        external_links:
            - lol-dev-db
    nginx:
        build:
            context: .
            dockerfile: docker/dev/nginx/Dockerfile
            target: nginx-dev
        image: loadorderlibrary-nginx:dev
        container_name: lol-dev-nginx
        restart: unless-stopped
        ports:
            - '8001:80'
        volumes:
            - ./public:/srv/dev.loadorderlibrary.com/public
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - /var/log/nginx/:/var/log/nginx
        networks:
            - lol
        depends_on: [app]

networks:
    lol:
        external: true
    lol-db:
        external: true

volumes:
    lol-testing-db:
