---
# Docker compose file for production environment

services:
    app:
        image: ghcr.io/phinocio/loadorderlibrary:latest
        container_name: lol-prod-app
        restart: unless-stopped
        entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan view:cache && exec php-fpm"
        env_file: .env
        user: '2100:2100'
        volumes:
            - ./storage:/srv/loadorderlibrary.com/storage
            - /srv/api.loadorderlibrary.com/storage/app/uploads:/srv/loadorderlibrary.com/storage/app/uploads
        networks:
            - lol
            - lol-db
        external_links:
            - lol-prod-db
    nginx:
        image: ghcr.io/phinocio/loadorderlibrary-nginx:latest
        container_name: lol-prod-nginx
        restart: unless-stopped
        networks:
            - lol
        depends_on: [app]

networks:
    lol:
        external: true
    lol-db:
        external: true

volumes:
    lol-prod-db:
