---
# Docker compose file for testing environment

services:
    app:
        image: ghcr.io/phinocio/loadorderlibrary:testing
        container_name: lol-testing-app
        restart: unless-stopped
        entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan view:cache && exec php-fpm"
        env_file: .env
        user: '2100:2100'
        profiles: ['testing', 'local']
        volumes:
            - ./storage/:/var/www/storage
            - /srv/testingapi.loadorderlibrary.com/storage/app/uploads:/var/www/storage/app/uploads
        networks:
            - lol
            - lol-db
        external_links:
            - lol-testing-db
    nginx:
        image: ghcr.io/phinocio/loadorderlibrary-nginx:testing
        container_name: lol-testing-nginx
        restart: unless-stopped
        profiles: ['testing', 'local']
        networks:
            - lol
        depends_on: [app]

networks:
    lol:
        external: true
    lol-db:
        external: true
